#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HelloFacebookXamarinAndroidSample.Resource", IsApplication=true)]

namespace HelloFacebookXamarinAndroidSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int abc_fade_in = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int abc_fade_out = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int abc_slide_in_bottom = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int abc_slide_in_top = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int abc_slide_out_bottom = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int abc_slide_out_top = 2131034117;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01001a
			public const int actionBarDivider = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int actionBarItemBackground = 2130771995;
			
			// aapt resource value: 0x7f010019
			public const int actionBarSize = 2130771993;
			
			// aapt resource value: 0x7f010017
			public const int actionBarSplitStyle = 2130771991;
			
			// aapt resource value: 0x7f010016
			public const int actionBarStyle = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int actionBarTabBarStyle = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int actionBarTabStyle = 2130771986;
			
			// aapt resource value: 0x7f010014
			public const int actionBarTabTextStyle = 2130771988;
			
			// aapt resource value: 0x7f010018
			public const int actionBarWidgetTheme = 2130771992;
			
			// aapt resource value: 0x7f010021
			public const int actionButtonStyle = 2130772001;
			
			// aapt resource value: 0x7f010052
			public const int actionDropDownStyle = 2130772050;
			
			// aapt resource value: 0x7f010059
			public const int actionLayout = 2130772057;
			
			// aapt resource value: 0x7f01001c
			public const int actionMenuTextAppearance = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int actionMenuTextColor = 2130771997;
			
			// aapt resource value: 0x7f010047
			public const int actionModeBackground = 2130772039;
			
			// aapt resource value: 0x7f010046
			public const int actionModeCloseButtonStyle = 2130772038;
			
			// aapt resource value: 0x7f010049
			public const int actionModeCloseDrawable = 2130772041;
			
			// aapt resource value: 0x7f01004b
			public const int actionModeCopyDrawable = 2130772043;
			
			// aapt resource value: 0x7f01004a
			public const int actionModeCutDrawable = 2130772042;
			
			// aapt resource value: 0x7f01004f
			public const int actionModeFindDrawable = 2130772047;
			
			// aapt resource value: 0x7f01004c
			public const int actionModePasteDrawable = 2130772044;
			
			// aapt resource value: 0x7f010051
			public const int actionModePopupWindowStyle = 2130772049;
			
			// aapt resource value: 0x7f01004d
			public const int actionModeSelectAllDrawable = 2130772045;
			
			// aapt resource value: 0x7f01004e
			public const int actionModeShareDrawable = 2130772046;
			
			// aapt resource value: 0x7f010048
			public const int actionModeSplitBackground = 2130772040;
			
			// aapt resource value: 0x7f010045
			public const int actionModeStyle = 2130772037;
			
			// aapt resource value: 0x7f010050
			public const int actionModeWebSearchDrawable = 2130772048;
			
			// aapt resource value: 0x7f010015
			public const int actionOverflowButtonStyle = 2130771989;
			
			// aapt resource value: 0x7f01005b
			public const int actionProviderClass = 2130772059;
			
			// aapt resource value: 0x7f01005a
			public const int actionViewClass = 2130772058;
			
			// aapt resource value: 0x7f010077
			public const int activityChooserViewStyle = 2130772087;
			
			// aapt resource value: 0x7f01003a
			public const int background = 2130772026;
			
			// aapt resource value: 0x7f01003c
			public const int backgroundSplit = 2130772028;
			
			// aapt resource value: 0x7f01003b
			public const int backgroundStacked = 2130772027;
			
			// aapt resource value: 0x7f010023
			public const int buttonBarButtonStyle = 2130772003;
			
			// aapt resource value: 0x7f010022
			public const int buttonBarStyle = 2130772002;
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f01007d
			public const int com_facebook_auxiliary_view_position = 2130772093;
			
			// aapt resource value: 0x7f01007f
			public const int com_facebook_confirm_logout = 2130772095;
			
			// aapt resource value: 0x7f010079
			public const int com_facebook_foreground_color = 2130772089;
			
			// aapt resource value: 0x7f01007e
			public const int com_facebook_horizontal_alignment = 2130772094;
			
			// aapt resource value: 0x7f010084
			public const int com_facebook_is_cropped = 2130772100;
			
			// aapt resource value: 0x7f010080
			public const int com_facebook_login_text = 2130772096;
			
			// aapt resource value: 0x7f010081
			public const int com_facebook_logout_text = 2130772097;
			
			// aapt resource value: 0x7f01007a
			public const int com_facebook_object_id = 2130772090;
			
			// aapt resource value: 0x7f01007b
			public const int com_facebook_object_type = 2130772091;
			
			// aapt resource value: 0x7f010083
			public const int com_facebook_preset_size = 2130772099;
			
			// aapt resource value: 0x7f01007c
			public const int com_facebook_style = 2130772092;
			
			// aapt resource value: 0x7f010082
			public const int com_facebook_tooltip_mode = 2130772098;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f01003d
			public const int customNavigationLayout = 2130772029;
			
			// aapt resource value: 0x7f01005f
			public const int disableChildrenWhenDisabled = 2130772063;
			
			// aapt resource value: 0x7f010033
			public const int displayOptions = 2130772019;
			
			// aapt resource value: 0x7f010039
			public const int divider = 2130772025;
			
			// aapt resource value: 0x7f010026
			public const int dividerHorizontal = 2130772006;
			
			// aapt resource value: 0x7f010061
			public const int dividerPadding = 2130772065;
			
			// aapt resource value: 0x7f010025
			public const int dividerVertical = 2130772005;
			
			// aapt resource value: 0x7f01002c
			public const int dropDownListViewStyle = 2130772012;
			
			// aapt resource value: 0x7f010053
			public const int dropdownListPreferredItemHeight = 2130772051;
			
			// aapt resource value: 0x7f010076
			public const int expandActivityOverflowButtonDrawable = 2130772086;
			
			// aapt resource value: 0x7f010031
			public const int height = 2130772017;
			
			// aapt resource value: 0x7f01001e
			public const int homeAsUpIndicator = 2130771998;
			
			// aapt resource value: 0x7f01003e
			public const int homeLayout = 2130772030;
			
			// aapt resource value: 0x7f010037
			public const int icon = 2130772023;
			
			// aapt resource value: 0x7f010065
			public const int iconifiedByDefault = 2130772069;
			
			// aapt resource value: 0x7f010040
			public const int indeterminateProgressStyle = 2130772032;
			
			// aapt resource value: 0x7f010075
			public const int initialActivityCount = 2130772085;
			
			// aapt resource value: 0x7f010064
			public const int isLightTheme = 2130772068;
			
			// aapt resource value: 0x7f010042
			public const int itemPadding = 2130772034;
			
			// aapt resource value: 0x7f010057
			public const int listChoiceBackgroundIndicator = 2130772055;
			
			// aapt resource value: 0x7f01002d
			public const int listPopupWindowStyle = 2130772013;
			
			// aapt resource value: 0x7f010027
			public const int listPreferredItemHeight = 2130772007;
			
			// aapt resource value: 0x7f010029
			public const int listPreferredItemHeightLarge = 2130772009;
			
			// aapt resource value: 0x7f010028
			public const int listPreferredItemHeightSmall = 2130772008;
			
			// aapt resource value: 0x7f01002a
			public const int listPreferredItemPaddingLeft = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int listPreferredItemPaddingRight = 2130772011;
			
			// aapt resource value: 0x7f010038
			public const int logo = 2130772024;
			
			// aapt resource value: 0x7f010032
			public const int navigationMode = 2130772018;
			
			// aapt resource value: 0x7f010044
			public const int paddingEnd = 2130772036;
			
			// aapt resource value: 0x7f010043
			public const int paddingStart = 2130772035;
			
			// aapt resource value: 0x7f010056
			public const int panelMenuListTheme = 2130772054;
			
			// aapt resource value: 0x7f010055
			public const int panelMenuListWidth = 2130772053;
			
			// aapt resource value: 0x7f010054
			public const int popupMenuStyle = 2130772052;
			
			// aapt resource value: 0x7f01005e
			public const int popupPromptView = 2130772062;
			
			// aapt resource value: 0x7f010041
			public const int progressBarPadding = 2130772033;
			
			// aapt resource value: 0x7f01003f
			public const int progressBarStyle = 2130772031;
			
			// aapt resource value: 0x7f01005c
			public const int prompt = 2130772060;
			
			// aapt resource value: 0x7f010066
			public const int queryHint = 2130772070;
			
			// aapt resource value: 0x7f010067
			public const int searchDropdownBackground = 2130772071;
			
			// aapt resource value: 0x7f010070
			public const int searchResultListItemHeight = 2130772080;
			
			// aapt resource value: 0x7f010074
			public const int searchViewAutoCompleteTextView = 2130772084;
			
			// aapt resource value: 0x7f010068
			public const int searchViewCloseIcon = 2130772072;
			
			// aapt resource value: 0x7f01006c
			public const int searchViewEditQuery = 2130772076;
			
			// aapt resource value: 0x7f01006d
			public const int searchViewEditQueryBackground = 2130772077;
			
			// aapt resource value: 0x7f010069
			public const int searchViewGoIcon = 2130772073;
			
			// aapt resource value: 0x7f01006a
			public const int searchViewSearchIcon = 2130772074;
			
			// aapt resource value: 0x7f01006e
			public const int searchViewTextField = 2130772078;
			
			// aapt resource value: 0x7f01006f
			public const int searchViewTextFieldRight = 2130772079;
			
			// aapt resource value: 0x7f01006b
			public const int searchViewVoiceIcon = 2130772075;
			
			// aapt resource value: 0x7f010024
			public const int selectableItemBackground = 2130772004;
			
			// aapt resource value: 0x7f010058
			public const int showAsAction = 2130772056;
			
			// aapt resource value: 0x7f010060
			public const int showDividers = 2130772064;
			
			// aapt resource value: 0x7f010063
			public const int spinnerDropDownItemStyle = 2130772067;
			
			// aapt resource value: 0x7f01005d
			public const int spinnerMode = 2130772061;
			
			// aapt resource value: 0x7f010062
			public const int spinnerStyle = 2130772066;
			
			// aapt resource value: 0x7f010034
			public const int subtitle = 2130772020;
			
			// aapt resource value: 0x7f010036
			public const int subtitleTextStyle = 2130772022;
			
			// aapt resource value: 0x7f010078
			public const int textAllCaps = 2130772088;
			
			// aapt resource value: 0x7f01001f
			public const int textAppearanceLargePopupMenu = 2130771999;
			
			// aapt resource value: 0x7f01002e
			public const int textAppearanceListItem = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int textAppearanceListItemSmall = 2130772015;
			
			// aapt resource value: 0x7f010072
			public const int textAppearanceSearchResultSubtitle = 2130772082;
			
			// aapt resource value: 0x7f010071
			public const int textAppearanceSearchResultTitle = 2130772081;
			
			// aapt resource value: 0x7f010020
			public const int textAppearanceSmallPopupMenu = 2130772000;
			
			// aapt resource value: 0x7f010073
			public const int textColorSearchUrl = 2130772083;
			
			// aapt resource value: 0x7f010030
			public const int title = 2130772016;
			
			// aapt resource value: 0x7f010035
			public const int titleTextStyle = 2130772021;
			
			// aapt resource value: 0x7f01000b
			public const int windowActionBar = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int windowActionBarOverlay = 2130771980;
			
			// aapt resource value: 0x7f010011
			public const int windowFixedHeightMajor = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public const int windowFixedHeightMinor = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int windowFixedWidthMajor = 2130771982;
			
			// aapt resource value: 0x7f010010
			public const int windowFixedWidthMinor = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int windowSplitActionBar = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs_pre_jb = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int abc_action_bar_expanded_action_views_exclusive = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int abc_config_actionMenuItemAllCaps = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int abc_config_allowActionMenuItemTextWithIcon = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int abc_config_showMenuShortcutsWhenKeyboardPresent = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int abc_split_action_bar_is_narrow = 2131296258;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060019
			public const int abc_search_url_text_holo = 2131099673;
			
			// aapt resource value: 0x7f060004
			public const int abc_search_url_text_normal = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int abc_search_url_text_pressed = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int abc_search_url_text_selected = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int cardview_dark_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_light_background = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_shadow_end_color = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int cardview_shadow_start_color = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_blue = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_button_background_color = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_button_background_color_disabled = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_button_background_color_focused = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_button_background_color_focused_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_button_background_color_pressed = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_button_background_color_selected = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_button_border_color_focused = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_button_login_silver_background_color = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_button_login_silver_background_color_pressed = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_button_send_background_color = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_button_send_background_color_pressed = 2131099666;
			
			// aapt resource value: 0x7f06001a
			public const int com_facebook_button_text_color = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int com_facebook_device_auth_text = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int com_facebook_likeboxcountview_border_color = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int com_facebook_likeboxcountview_text_color = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int com_facebook_likeview_text_color = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int com_facebook_messenger_blue = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int com_facebook_send_button_text_color = 2131099675;
			
			// aapt resource value: 0x7f060018
			public const int com_facebook_share_button_text_color = 2131099672;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070005
			public const int abc_action_bar_default_height = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int abc_action_bar_icon_vertical_padding = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int abc_action_bar_progress_bar_size = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int abc_action_bar_stacked_max_height = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int abc_action_bar_stacked_tab_max_width = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int abc_action_bar_subtitle_bottom_margin = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int abc_action_bar_subtitle_text_size = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int abc_action_bar_subtitle_top_margin = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int abc_action_bar_title_text_size = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int abc_action_button_min_width = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int abc_config_prefDialogWidth = 2131165187;
			
			// aapt resource value: 0x7f070013
			public const int abc_dropdownitem_icon_width = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int abc_dropdownitem_text_padding_left = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int abc_dropdownitem_text_padding_right = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int abc_panel_menu_list_width = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int abc_search_view_preferred_width = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int abc_search_view_text_min_width = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int cardview_compat_inset_shadow = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_default_elevation = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_default_radius = 2131165186;
			
			// aapt resource value: 0x7f070018
			public const int com_facebook_auth_dialog_corner_radius = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int com_facebook_auth_dialog_corner_radius_oversized = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int com_facebook_button_corner_radius = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int com_facebook_likeboxcountview_border_radius = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int com_facebook_likeboxcountview_border_width = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int com_facebook_likeboxcountview_caret_height = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int com_facebook_likeboxcountview_caret_width = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int com_facebook_likeboxcountview_text_padding = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int com_facebook_likeboxcountview_text_size = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int com_facebook_likeview_edge_padding = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int com_facebook_likeview_internal_padding = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int com_facebook_likeview_text_size = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int com_facebook_profilepictureview_preset_size_large = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int com_facebook_profilepictureview_preset_size_normal = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int com_facebook_profilepictureview_preset_size_small = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int com_facebook_share_button_compound_drawable_padding = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int com_facebook_share_button_padding_bottom = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int com_facebook_share_button_padding_left = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int com_facebook_share_button_padding_right = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int com_facebook_share_button_padding_top = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int com_facebook_share_button_text_size = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int com_facebook_tooltip_horizontal_padding = 2131165229;
			
			// aapt resource value: 0x7f070016
			public const int dialog_fixed_height_major = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int dialog_fixed_height_minor = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int dialog_fixed_width_major = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int dialog_fixed_width_minor = 2131165205;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abc_ab_bottom_solid_dark_holo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int abc_ab_bottom_solid_light_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int abc_ab_bottom_transparent_dark_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int abc_ab_bottom_transparent_light_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int abc_ab_share_pack_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int abc_ab_share_pack_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int abc_ab_solid_dark_holo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int abc_ab_solid_light_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int abc_ab_stacked_solid_dark_holo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int abc_ab_stacked_solid_light_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int abc_ab_stacked_transparent_dark_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int abc_ab_stacked_transparent_light_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int abc_ab_transparent_dark_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int abc_ab_transparent_light_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int abc_cab_background_bottom_holo_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int abc_cab_background_bottom_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int abc_cab_background_top_holo_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int abc_cab_background_top_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int abc_ic_ab_back_holo_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int abc_ic_ab_back_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int abc_ic_cab_done_holo_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int abc_ic_cab_done_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int abc_ic_clear = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int abc_ic_clear_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int abc_ic_clear_holo_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int abc_ic_clear_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int abc_ic_clear_search_api_disabled_holo_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int abc_ic_clear_search_api_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int abc_ic_commit_search_api_holo_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int abc_ic_commit_search_api_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int abc_ic_go = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int abc_ic_go_search_api_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int abc_ic_menu_moreoverflow_normal_holo_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int abc_ic_menu_moreoverflow_normal_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int abc_ic_menu_share_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int abc_ic_menu_share_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int abc_ic_search = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int abc_ic_search_api_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int abc_ic_voice_search = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int abc_ic_voice_search_api_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int abc_item_background_holo_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int abc_item_background_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int abc_list_divider_holo_dark = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int abc_list_divider_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int abc_list_focused_holo = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int abc_list_longpressed_holo = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int abc_list_pressed_holo_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int abc_list_pressed_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int abc_list_selector_background_transition_holo_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int abc_list_selector_background_transition_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int abc_list_selector_disabled_holo_dark = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int abc_list_selector_disabled_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int abc_list_selector_holo_dark = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int abc_list_selector_holo_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int abc_menu_dropdown_panel_holo_dark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int abc_menu_dropdown_panel_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int abc_menu_hardkey_panel_holo_dark = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int abc_menu_hardkey_panel_holo_light = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int abc_search_dropdown_dark = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int abc_search_dropdown_light = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int abc_spinner_ab_default_holo_dark = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int abc_spinner_ab_default_holo_light = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int abc_spinner_ab_disabled_holo_dark = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int abc_spinner_ab_disabled_holo_light = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int abc_spinner_ab_focused_holo_dark = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int abc_spinner_ab_focused_holo_light = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int abc_spinner_ab_holo_dark = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int abc_spinner_ab_holo_light = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int abc_spinner_ab_pressed_holo_dark = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int abc_spinner_ab_pressed_holo_light = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int abc_tab_indicator_ab_holo = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int abc_tab_selected_focused_holo = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int abc_tab_selected_holo = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int abc_tab_selected_pressed_holo = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int abc_tab_unselected_pressed_holo = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int abc_textfield_search_default_holo_dark = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int abc_textfield_search_default_holo_light = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int abc_textfield_search_right_default_holo_dark = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int abc_textfield_search_right_default_holo_light = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int abc_textfield_search_right_selected_holo_dark = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int abc_textfield_search_right_selected_holo_light = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int abc_textfield_search_selected_holo_dark = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int abc_textfield_search_selected_holo_light = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int abc_textfield_searchview_holo_dark = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int abc_textfield_searchview_holo_light = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int abc_textfield_searchview_right_holo_dark = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int abc_textfield_searchview_right_holo_light = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int com_facebook_auth_dialog_background = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int com_facebook_auth_dialog_cancel_background = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int com_facebook_auth_dialog_header_background = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int com_facebook_button_background = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int com_facebook_button_icon = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int com_facebook_button_icon_blue = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int com_facebook_button_icon_white = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int com_facebook_button_like_background = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int com_facebook_button_like_icon_selected = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int com_facebook_button_login_silver_background = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int com_facebook_button_send_background = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int com_facebook_button_send_icon_blue = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int com_facebook_button_send_icon_white = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int com_facebook_close = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int com_facebook_favicon_white = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int com_facebook_profile_picture_blank_portrait = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int com_facebook_profile_picture_blank_square = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int com_facebook_send_button_icon = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int com_facebook_tooltip_black_background = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int com_facebook_tooltip_black_bottomnub = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int com_facebook_tooltip_black_topnub = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int com_facebook_tooltip_black_xout = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int com_facebook_tooltip_blue_background = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int com_facebook_tooltip_blue_bottomnub = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int com_facebook_tooltip_blue_topnub = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int com_facebook_tooltip_blue_xout = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int icon = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int messenger_bubble_large_blue = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int messenger_bubble_large_white = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int messenger_bubble_small_blue = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int messenger_bubble_small_white = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int messenger_button_blue_bg_round = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int messenger_button_blue_bg_selector = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int messenger_button_send_round_shadow = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int messenger_button_white_bg_round = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int messenger_button_white_bg_selector = 2130837626;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b002d
			public const int action_bar = 2131427373;
			
			// aapt resource value: 0x7f0b0001
			public const int action_bar_activity_content = 2131427329;
			
			// aapt resource value: 0x7f0b002c
			public const int action_bar_container = 2131427372;
			
			// aapt resource value: 0x7f0b0030
			public const int action_bar_overlay_layout = 2131427376;
			
			// aapt resource value: 0x7f0b002b
			public const int action_bar_root = 2131427371;
			
			// aapt resource value: 0x7f0b0034
			public const int action_bar_subtitle = 2131427380;
			
			// aapt resource value: 0x7f0b0033
			public const int action_bar_title = 2131427379;
			
			// aapt resource value: 0x7f0b002e
			public const int action_context_bar = 2131427374;
			
			// aapt resource value: 0x7f0b0002
			public const int action_menu_divider = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int action_menu_presenter = 2131427331;
			
			// aapt resource value: 0x7f0b0035
			public const int action_mode_close_button = 2131427381;
			
			// aapt resource value: 0x7f0b0036
			public const int activity_chooser_view_content = 2131427382;
			
			// aapt resource value: 0x7f0b000f
			public const int always = 2131427343;
			
			// aapt resource value: 0x7f0b0026
			public const int automatic = 2131427366;
			
			// aapt resource value: 0x7f0b0016
			public const int beginning = 2131427350;
			
			// aapt resource value: 0x7f0b0020
			public const int bottom = 2131427360;
			
			// aapt resource value: 0x7f0b001d
			public const int box_count = 2131427357;
			
			// aapt resource value: 0x7f0b001e
			public const int button = 2131427358;
			
			// aapt resource value: 0x7f0b0052
			public const int cancel_button = 2131427410;
			
			// aapt resource value: 0x7f0b0023
			public const int center = 2131427363;
			
			// aapt resource value: 0x7f0b003e
			public const int checkbox = 2131427390;
			
			// aapt resource value: 0x7f0b0010
			public const int collapseActionView = 2131427344;
			
			// aapt resource value: 0x7f0b0054
			public const int com_facebook_body_frame = 2131427412;
			
			// aapt resource value: 0x7f0b0056
			public const int com_facebook_button_xout = 2131427414;
			
			// aapt resource value: 0x7f0b004f
			public const int com_facebook_device_auth_instructions = 2131427407;
			
			// aapt resource value: 0x7f0b004d
			public const int com_facebook_fragment_container = 2131427405;
			
			// aapt resource value: 0x7f0b0053
			public const int com_facebook_login_activity_progress_bar = 2131427411;
			
			// aapt resource value: 0x7f0b0058
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131427416;
			
			// aapt resource value: 0x7f0b0057
			public const int com_facebook_tooltip_bubble_view_text_body = 2131427415;
			
			// aapt resource value: 0x7f0b0055
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131427413;
			
			// aapt resource value: 0x7f0b0050
			public const int confirmation_code = 2131427408;
			
			// aapt resource value: 0x7f0b0039
			public const int default_activity_button = 2131427385;
			
			// aapt resource value: 0x7f0b0014
			public const int dialog = 2131427348;
			
			// aapt resource value: 0x7f0b0009
			public const int disableHome = 2131427337;
			
			// aapt resource value: 0x7f0b0027
			public const int display_always = 2131427367;
			
			// aapt resource value: 0x7f0b0015
			public const int dropdown = 2131427349;
			
			// aapt resource value: 0x7f0b0041
			public const int edit_query = 2131427393;
			
			// aapt resource value: 0x7f0b0017
			public const int end = 2131427351;
			
			// aapt resource value: 0x7f0b0037
			public const int expand_activities_button = 2131427383;
			
			// aapt resource value: 0x7f0b003d
			public const int expanded_menu = 2131427389;
			
			// aapt resource value: 0x7f0b005a
			public const int greeting = 2131427418;
			
			// aapt resource value: 0x7f0b0000
			public const int home = 2131427328;
			
			// aapt resource value: 0x7f0b000a
			public const int homeAsUp = 2131427338;
			
			// aapt resource value: 0x7f0b003b
			public const int icon = 2131427387;
			
			// aapt resource value: 0x7f0b0011
			public const int ifRoom = 2131427345;
			
			// aapt resource value: 0x7f0b0038
			public const int image = 2131427384;
			
			// aapt resource value: 0x7f0b0021
			public const int inline = 2131427361;
			
			// aapt resource value: 0x7f0b0029
			public const int large = 2131427369;
			
			// aapt resource value: 0x7f0b0024
			public const int left = 2131427364;
			
			// aapt resource value: 0x7f0b0006
			public const int listMode = 2131427334;
			
			// aapt resource value: 0x7f0b003a
			public const int list_item = 2131427386;
			
			// aapt resource value: 0x7f0b0059
			public const int main_ui_container = 2131427417;
			
			// aapt resource value: 0x7f0b005e
			public const int messenger_send_button = 2131427422;
			
			// aapt resource value: 0x7f0b0018
			public const int middle = 2131427352;
			
			// aapt resource value: 0x7f0b0012
			public const int never = 2131427346;
			
			// aapt resource value: 0x7f0b0028
			public const int never_display = 2131427368;
			
			// aapt resource value: 0x7f0b0019
			public const int none = 2131427353;
			
			// aapt resource value: 0x7f0b0007
			public const int normal = 2131427335;
			
			// aapt resource value: 0x7f0b001a
			public const int open_graph = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int page = 2131427355;
			
			// aapt resource value: 0x7f0b005d
			public const int postPhotoButton = 2131427421;
			
			// aapt resource value: 0x7f0b005c
			public const int postStatusUpdateButton = 2131427420;
			
			// aapt resource value: 0x7f0b005b
			public const int profilePicture = 2131427419;
			
			// aapt resource value: 0x7f0b0051
			public const int progress_bar = 2131427409;
			
			// aapt resource value: 0x7f0b0004
			public const int progress_circular = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int progress_horizontal = 2131427333;
			
			// aapt resource value: 0x7f0b0040
			public const int radio = 2131427392;
			
			// aapt resource value: 0x7f0b0025
			public const int right = 2131427365;
			
			// aapt resource value: 0x7f0b0043
			public const int search_badge = 2131427395;
			
			// aapt resource value: 0x7f0b0042
			public const int search_bar = 2131427394;
			
			// aapt resource value: 0x7f0b0044
			public const int search_button = 2131427396;
			
			// aapt resource value: 0x7f0b0049
			public const int search_close_btn = 2131427401;
			
			// aapt resource value: 0x7f0b0045
			public const int search_edit_frame = 2131427397;
			
			// aapt resource value: 0x7f0b004b
			public const int search_go_btn = 2131427403;
			
			// aapt resource value: 0x7f0b0046
			public const int search_mag_icon = 2131427398;
			
			// aapt resource value: 0x7f0b0047
			public const int search_plate = 2131427399;
			
			// aapt resource value: 0x7f0b0048
			public const int search_src_text = 2131427400;
			
			// aapt resource value: 0x7f0b004c
			public const int search_voice_btn = 2131427404;
			
			// aapt resource value: 0x7f0b003f
			public const int shortcut = 2131427391;
			
			// aapt resource value: 0x7f0b000b
			public const int showCustom = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int showHome = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int showTitle = 2131427341;
			
			// aapt resource value: 0x7f0b002a
			public const int small = 2131427370;
			
			// aapt resource value: 0x7f0b002f
			public const int split_action_bar = 2131427375;
			
			// aapt resource value: 0x7f0b001f
			public const int standard = 2131427359;
			
			// aapt resource value: 0x7f0b004a
			public const int submit_area = 2131427402;
			
			// aapt resource value: 0x7f0b0008
			public const int tabMode = 2131427336;
			
			// aapt resource value: 0x7f0b004e
			public const int textView = 2131427406;
			
			// aapt resource value: 0x7f0b003c
			public const int title = 2131427388;
			
			// aapt resource value: 0x7f0b0022
			public const int top = 2131427362;
			
			// aapt resource value: 0x7f0b0031
			public const int top_action_bar = 2131427377;
			
			// aapt resource value: 0x7f0b001c
			public const int unknown = 2131427356;
			
			// aapt resource value: 0x7f0b0032
			public const int up = 2131427378;
			
			// aapt resource value: 0x7f0b000e
			public const int useLogo = 2131427342;
			
			// aapt resource value: 0x7f0b0013
			public const int withText = 2131427347;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int abc_max_action_buttons = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int abc_action_bar_decor = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int abc_action_bar_decor_include = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int abc_action_bar_decor_overlay = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int abc_action_bar_home = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int abc_action_bar_tab = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int abc_action_bar_tabbar = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int abc_action_bar_title_item = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int abc_action_bar_view_list_nav_layout = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int abc_action_menu_item_layout = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int abc_action_menu_layout = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int abc_action_mode_bar = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int abc_action_mode_close_item = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int abc_activity_chooser_view = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int abc_activity_chooser_view_include = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int abc_activity_chooser_view_list_item = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int abc_expanded_menu_layout = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int abc_list_menu_item_checkbox = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int abc_list_menu_item_icon = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int abc_list_menu_item_layout = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int abc_list_menu_item_radio = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int abc_popup_menu_item_layout = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int abc_search_dropdown_item_icons_2line = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int abc_search_view = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int abc_simple_decor = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int com_facebook_activity_layout = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int com_facebook_device_auth_dialog_fragment = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int com_facebook_login_fragment = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int com_facebook_tooltip_bubble = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int Main = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int messenger_button_send_blue_large = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int messenger_button_send_blue_round = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int messenger_button_send_blue_small = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int messenger_button_send_white_large = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int messenger_button_send_white_round = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int messenger_button_send_white_small = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int support_simple_spinner_dropdown_item = 2130968611;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0c0001
			public const int abc_action_bar_home_description = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int abc_action_bar_up_description = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int abc_action_menu_overflow_description = 2131492867;
			
			// aapt resource value: 0x7f0c0000
			public const int abc_action_mode_done = 2131492864;
			
			// aapt resource value: 0x7f0c000a
			public const int abc_activity_chooser_view_see_all = 2131492874;
			
			// aapt resource value: 0x7f0c0009
			public const int abc_activitychooserview_choose_application = 2131492873;
			
			// aapt resource value: 0x7f0c0006
			public const int abc_searchview_description_clear = 2131492870;
			
			// aapt resource value: 0x7f0c0005
			public const int abc_searchview_description_query = 2131492869;
			
			// aapt resource value: 0x7f0c0004
			public const int abc_searchview_description_search = 2131492868;
			
			// aapt resource value: 0x7f0c0007
			public const int abc_searchview_description_submit = 2131492871;
			
			// aapt resource value: 0x7f0c0008
			public const int abc_searchview_description_voice = 2131492872;
			
			// aapt resource value: 0x7f0c000c
			public const int abc_shareactionprovider_share_with = 2131492876;
			
			// aapt resource value: 0x7f0c000b
			public const int abc_shareactionprovider_share_with_application = 2131492875;
			
			// aapt resource value: 0x7f0c001f
			public const int app_name = 2131492895;
			
			// aapt resource value: 0x7f0c0021
			public const int cancelled = 2131492897;
			
			// aapt resource value: 0x7f0c000d
			public const int com_facebook_device_auth_instructions = 2131492877;
			
			// aapt resource value: 0x7f0c000e
			public const int com_facebook_image_download_unknown_error = 2131492878;
			
			// aapt resource value: 0x7f0c000f
			public const int com_facebook_internet_permission_error_message = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int com_facebook_internet_permission_error_title = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int com_facebook_like_button_liked = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public const int com_facebook_like_button_not_liked = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public const int com_facebook_loading = 2131492883;
			
			// aapt resource value: 0x7f0c0014
			public const int com_facebook_loginview_cancel_action = 2131492884;
			
			// aapt resource value: 0x7f0c0015
			public const int com_facebook_loginview_log_in_button = 2131492885;
			
			// aapt resource value: 0x7f0c0016
			public const int com_facebook_loginview_log_in_button_long = 2131492886;
			
			// aapt resource value: 0x7f0c0017
			public const int com_facebook_loginview_log_out_action = 2131492887;
			
			// aapt resource value: 0x7f0c0018
			public const int com_facebook_loginview_log_out_button = 2131492888;
			
			// aapt resource value: 0x7f0c0019
			public const int com_facebook_loginview_logged_in_as = 2131492889;
			
			// aapt resource value: 0x7f0c001a
			public const int com_facebook_loginview_logged_in_using_facebook = 2131492890;
			
			// aapt resource value: 0x7f0c001b
			public const int com_facebook_send_button_text = 2131492891;
			
			// aapt resource value: 0x7f0c001c
			public const int com_facebook_share_button_text = 2131492892;
			
			// aapt resource value: 0x7f0c001d
			public const int com_facebook_tooltip_default = 2131492893;
			
			// aapt resource value: 0x7f0c0027
			public const int error = 2131492903;
			
			// aapt resource value: 0x7f0c002f
			public const int exception = 2131492911;
			
			// aapt resource value: 0x7f0c002e
			public const int facebook_app_id = 2131492910;
			
			// aapt resource value: 0x7f0c0020
			public const int facebook_app_name = 2131492896;
			
			// aapt resource value: 0x7f0c0024
			public const int hello_user = 2131492900;
			
			// aapt resource value: 0x7f0c001e
			public const int messenger_send_button_text = 2131492894;
			
			// aapt resource value: 0x7f0c002b
			public const int no_friends_selected = 2131492907;
			
			// aapt resource value: 0x7f0c002c
			public const int no_place_selected = 2131492908;
			
			// aapt resource value: 0x7f0c0023
			public const int ok = 2131492899;
			
			// aapt resource value: 0x7f0c0022
			public const int permission_not_granted = 2131492898;
			
			// aapt resource value: 0x7f0c0029
			public const int photo_post = 2131492905;
			
			// aapt resource value: 0x7f0c002d
			public const int pick_seattle_place = 2131492909;
			
			// aapt resource value: 0x7f0c0028
			public const int status_update = 2131492904;
			
			// aapt resource value: 0x7f0c0025
			public const int success = 2131492901;
			
			// aapt resource value: 0x7f0c0026
			public const int successfully_posted_post = 2131492902;
			
			// aapt resource value: 0x7f0c002a
			public const int you_picked = 2131492906;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int CardView = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int CardView_Dark = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int CardView_Light = 2131230722;
			
			// aapt resource value: 0x7f08008e
			public const int MessengerButton = 2131230862;
			
			// aapt resource value: 0x7f08008f
			public const int MessengerButton_Blue = 2131230863;
			
			// aapt resource value: 0x7f080090
			public const int MessengerButton_Blue_Large = 2131230864;
			
			// aapt resource value: 0x7f080091
			public const int MessengerButton_Blue_Small = 2131230865;
			
			// aapt resource value: 0x7f080092
			public const int MessengerButton_White = 2131230866;
			
			// aapt resource value: 0x7f080093
			public const int MessengerButton_White_Large = 2131230867;
			
			// aapt resource value: 0x7f080094
			public const int MessengerButton_White_Small = 2131230868;
			
			// aapt resource value: 0x7f080095
			public const int MessengerButtonText = 2131230869;
			
			// aapt resource value: 0x7f080096
			public const int MessengerButtonText_Blue = 2131230870;
			
			// aapt resource value: 0x7f080097
			public const int MessengerButtonText_Blue_Large = 2131230871;
			
			// aapt resource value: 0x7f080098
			public const int MessengerButtonText_Blue_Small = 2131230872;
			
			// aapt resource value: 0x7f080099
			public const int MessengerButtonText_White = 2131230873;
			
			// aapt resource value: 0x7f08009a
			public const int MessengerButtonText_White_Large = 2131230874;
			
			// aapt resource value: 0x7f08009b
			public const int MessengerButtonText_White_Small = 2131230875;
			
			// aapt resource value: 0x7f080066
			public const int TextAppearance_AppCompat_Base_CompactMenu_Dialog = 2131230822;
			
			// aapt resource value: 0x7f080070
			public const int TextAppearance_AppCompat_Base_SearchResult = 2131230832;
			
			// aapt resource value: 0x7f080072
			public const int TextAppearance_AppCompat_Base_SearchResult_Subtitle = 2131230834;
			
			// aapt resource value: 0x7f080071
			public const int TextAppearance_AppCompat_Base_SearchResult_Title = 2131230833;
			
			// aapt resource value: 0x7f08006c
			public const int TextAppearance_AppCompat_Base_Widget_PopupMenu_Large = 2131230828;
			
			// aapt resource value: 0x7f08006d
			public const int TextAppearance_AppCompat_Base_Widget_PopupMenu_Small = 2131230829;
			
			// aapt resource value: 0x7f080073
			public const int TextAppearance_AppCompat_Light_Base_SearchResult = 2131230835;
			
			// aapt resource value: 0x7f080075
			public const int TextAppearance_AppCompat_Light_Base_SearchResult_Subtitle = 2131230837;
			
			// aapt resource value: 0x7f080074
			public const int TextAppearance_AppCompat_Light_Base_SearchResult_Title = 2131230836;
			
			// aapt resource value: 0x7f08006e
			public const int TextAppearance_AppCompat_Light_Base_Widget_PopupMenu_Large = 2131230830;
			
			// aapt resource value: 0x7f08006f
			public const int TextAppearance_AppCompat_Light_Base_Widget_PopupMenu_Small = 2131230831;
			
			// aapt resource value: 0x7f080038
			public const int TextAppearance_AppCompat_Light_SearchResult_Subtitle = 2131230776;
			
			// aapt resource value: 0x7f080037
			public const int TextAppearance_AppCompat_Light_SearchResult_Title = 2131230775;
			
			// aapt resource value: 0x7f080033
			public const int TextAppearance_AppCompat_Light_Widget_PopupMenu_Large = 2131230771;
			
			// aapt resource value: 0x7f080034
			public const int TextAppearance_AppCompat_Light_Widget_PopupMenu_Small = 2131230772;
			
			// aapt resource value: 0x7f080036
			public const int TextAppearance_AppCompat_SearchResult_Subtitle = 2131230774;
			
			// aapt resource value: 0x7f080035
			public const int TextAppearance_AppCompat_SearchResult_Title = 2131230773;
			
			// aapt resource value: 0x7f08001d
			public const int TextAppearance_AppCompat_Widget_ActionBar_Menu = 2131230749;
			
			// aapt resource value: 0x7f080009
			public const int TextAppearance_AppCompat_Widget_ActionBar_Subtitle = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int TextAppearance_AppCompat_Widget_ActionBar_Subtitle_Inverse = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int TextAppearance_AppCompat_Widget_ActionBar_Title = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int TextAppearance_AppCompat_Widget_ActionBar_Title_Inverse = 2131230730;
			
			// aapt resource value: 0x7f080021
			public const int TextAppearance_AppCompat_Widget_ActionMode_Subtitle = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int TextAppearance_AppCompat_Widget_ActionMode_Subtitle_Inverse = 2131230755;
			
			// aapt resource value: 0x7f080020
			public const int TextAppearance_AppCompat_Widget_ActionMode_Title = 2131230752;
			
			// aapt resource value: 0x7f080022
			public const int TextAppearance_AppCompat_Widget_ActionMode_Title_Inverse = 2131230754;
			
			// aapt resource value: 0x7f080057
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Menu = 2131230807;
			
			// aapt resource value: 0x7f080059
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Subtitle = 2131230809;
			
			// aapt resource value: 0x7f08005b
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Subtitle_Inverse = 2131230811;
			
			// aapt resource value: 0x7f080058
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Title = 2131230808;
			
			// aapt resource value: 0x7f08005a
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Title_Inverse = 2131230810;
			
			// aapt resource value: 0x7f080054
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Subtitle = 2131230804;
			
			// aapt resource value: 0x7f080056
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Subtitle_Inverse = 2131230806;
			
			// aapt resource value: 0x7f080053
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Title = 2131230803;
			
			// aapt resource value: 0x7f080055
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Title_Inverse = 2131230805;
			
			// aapt resource value: 0x7f080064
			public const int TextAppearance_AppCompat_Widget_Base_DropDownItem = 2131230820;
			
			// aapt resource value: 0x7f080024
			public const int TextAppearance_AppCompat_Widget_DropDownItem = 2131230756;
			
			// aapt resource value: 0x7f080031
			public const int TextAppearance_AppCompat_Widget_PopupMenu_Large = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int TextAppearance_AppCompat_Widget_PopupMenu_Small = 2131230770;
			
			// aapt resource value: 0x7f080065
			public const int TextAppearance_Widget_AppCompat_Base_ExpandedMenu_Item = 2131230821;
			
			// aapt resource value: 0x7f08002b
			public const int TextAppearance_Widget_AppCompat_ExpandedMenu_Item = 2131230763;
			
			// aapt resource value: 0x7f08007a
			public const int Theme_AppCompat = 2131230842;
			
			// aapt resource value: 0x7f080086
			public const int Theme_AppCompat_Base_CompactMenu = 2131230854;
			
			// aapt resource value: 0x7f080087
			public const int Theme_AppCompat_Base_CompactMenu_Dialog = 2131230855;
			
			// aapt resource value: 0x7f08007f
			public const int Theme_AppCompat_CompactMenu = 2131230847;
			
			// aapt resource value: 0x7f080080
			public const int Theme_AppCompat_CompactMenu_Dialog = 2131230848;
			
			// aapt resource value: 0x7f08007d
			public const int Theme_AppCompat_DialogWhenLarge = 2131230845;
			
			// aapt resource value: 0x7f08007b
			public const int Theme_AppCompat_Light = 2131230843;
			
			// aapt resource value: 0x7f08007c
			public const int Theme_AppCompat_Light_DarkActionBar = 2131230844;
			
			// aapt resource value: 0x7f08007e
			public const int Theme_AppCompat_Light_DialogWhenLarge = 2131230846;
			
			// aapt resource value: 0x7f080081
			public const int Theme_Base = 2131230849;
			
			// aapt resource value: 0x7f080083
			public const int Theme_Base_AppCompat = 2131230851;
			
			// aapt resource value: 0x7f08008a
			public const int Theme_Base_AppCompat_Dialog_FixedSize = 2131230858;
			
			// aapt resource value: 0x7f08008b
			public const int Theme_Base_AppCompat_Dialog_Light_FixedSize = 2131230859;
			
			// aapt resource value: 0x7f080088
			public const int Theme_Base_AppCompat_DialogWhenLarge = 2131230856;
			
			// aapt resource value: 0x7f08008c
			public const int Theme_Base_AppCompat_DialogWhenLarge_Base = 2131230860;
			
			// aapt resource value: 0x7f080084
			public const int Theme_Base_AppCompat_Light = 2131230852;
			
			// aapt resource value: 0x7f080085
			public const int Theme_Base_AppCompat_Light_DarkActionBar = 2131230853;
			
			// aapt resource value: 0x7f080089
			public const int Theme_Base_AppCompat_Light_DialogWhenLarge = 2131230857;
			
			// aapt resource value: 0x7f08008d
			public const int Theme_Base_AppCompat_Light_DialogWhenLarge_Base = 2131230861;
			
			// aapt resource value: 0x7f080082
			public const int Theme_Base_Light = 2131230850;
			
			// aapt resource value: 0x7f080003
			public const int Widget_AppCompat_ActionBar = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int Widget_AppCompat_ActionBar_Solid = 2131230725;
			
			// aapt resource value: 0x7f080014
			public const int Widget_AppCompat_ActionBar_TabBar = 2131230740;
			
			// aapt resource value: 0x7f08001a
			public const int Widget_AppCompat_ActionBar_TabText = 2131230746;
			
			// aapt resource value: 0x7f080017
			public const int Widget_AppCompat_ActionBar_TabView = 2131230743;
			
			// aapt resource value: 0x7f08000e
			public const int Widget_AppCompat_ActionButton = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int Widget_AppCompat_ActionButton_CloseMode = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int Widget_AppCompat_ActionButton_Overflow = 2131230738;
			
			// aapt resource value: 0x7f08001e
			public const int Widget_AppCompat_ActionMode = 2131230750;
			
			// aapt resource value: 0x7f08003b
			public const int Widget_AppCompat_ActivityChooserView = 2131230779;
			
			// aapt resource value: 0x7f080039
			public const int Widget_AppCompat_AutoCompleteTextView = 2131230777;
			
			// aapt resource value: 0x7f08003d
			public const int Widget_AppCompat_Base_ActionBar = 2131230781;
			
			// aapt resource value: 0x7f08003f
			public const int Widget_AppCompat_Base_ActionBar_Solid = 2131230783;
			
			// aapt resource value: 0x7f080048
			public const int Widget_AppCompat_Base_ActionBar_TabBar = 2131230792;
			
			// aapt resource value: 0x7f08004e
			public const int Widget_AppCompat_Base_ActionBar_TabText = 2131230798;
			
			// aapt resource value: 0x7f08004b
			public const int Widget_AppCompat_Base_ActionBar_TabView = 2131230795;
			
			// aapt resource value: 0x7f080042
			public const int Widget_AppCompat_Base_ActionButton = 2131230786;
			
			// aapt resource value: 0x7f080044
			public const int Widget_AppCompat_Base_ActionButton_CloseMode = 2131230788;
			
			// aapt resource value: 0x7f080046
			public const int Widget_AppCompat_Base_ActionButton_Overflow = 2131230790;
			
			// aapt resource value: 0x7f080051
			public const int Widget_AppCompat_Base_ActionMode = 2131230801;
			
			// aapt resource value: 0x7f080078
			public const int Widget_AppCompat_Base_ActivityChooserView = 2131230840;
			
			// aapt resource value: 0x7f080076
			public const int Widget_AppCompat_Base_AutoCompleteTextView = 2131230838;
			
			// aapt resource value: 0x7f080060
			public const int Widget_AppCompat_Base_DropDownItem_Spinner = 2131230816;
			
			// aapt resource value: 0x7f080068
			public const int Widget_AppCompat_Base_ListPopupWindow = 2131230824;
			
			// aapt resource value: 0x7f080062
			public const int Widget_AppCompat_Base_ListView_DropDown = 2131230818;
			
			// aapt resource value: 0x7f080067
			public const int Widget_AppCompat_Base_ListView_Menu = 2131230823;
			
			// aapt resource value: 0x7f08006a
			public const int Widget_AppCompat_Base_PopupMenu = 2131230826;
			
			// aapt resource value: 0x7f08005d
			public const int Widget_AppCompat_Base_ProgressBar = 2131230813;
			
			// aapt resource value: 0x7f08005c
			public const int Widget_AppCompat_Base_ProgressBar_Horizontal = 2131230812;
			
			// aapt resource value: 0x7f08005e
			public const int Widget_AppCompat_Base_Spinner = 2131230814;
			
			// aapt resource value: 0x7f080027
			public const int Widget_AppCompat_DropDownItem_Spinner = 2131230759;
			
			// aapt resource value: 0x7f080004
			public const int Widget_AppCompat_Light_ActionBar = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int Widget_AppCompat_Light_ActionBar_Solid = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int Widget_AppCompat_Light_ActionBar_Solid_Inverse = 2131230727;
			
			// aapt resource value: 0x7f080015
			public const int Widget_AppCompat_Light_ActionBar_TabBar = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int Widget_AppCompat_Light_ActionBar_TabBar_Inverse = 2131230742;
			
			// aapt resource value: 0x7f08001b
			public const int Widget_AppCompat_Light_ActionBar_TabText = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int Widget_AppCompat_Light_ActionBar_TabText_Inverse = 2131230748;
			
			// aapt resource value: 0x7f080018
			public const int Widget_AppCompat_Light_ActionBar_TabView = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int Widget_AppCompat_Light_ActionBar_TabView_Inverse = 2131230745;
			
			// aapt resource value: 0x7f08000f
			public const int Widget_AppCompat_Light_ActionButton = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int Widget_AppCompat_Light_ActionButton_CloseMode = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int Widget_AppCompat_Light_ActionButton_Overflow = 2131230739;
			
			// aapt resource value: 0x7f08001f
			public const int Widget_AppCompat_Light_ActionMode_Inverse = 2131230751;
			
			// aapt resource value: 0x7f08003c
			public const int Widget_AppCompat_Light_ActivityChooserView = 2131230780;
			
			// aapt resource value: 0x7f08003a
			public const int Widget_AppCompat_Light_AutoCompleteTextView = 2131230778;
			
			// aapt resource value: 0x7f08003e
			public const int Widget_AppCompat_Light_Base_ActionBar = 2131230782;
			
			// aapt resource value: 0x7f080040
			public const int Widget_AppCompat_Light_Base_ActionBar_Solid = 2131230784;
			
			// aapt resource value: 0x7f080041
			public const int Widget_AppCompat_Light_Base_ActionBar_Solid_Inverse = 2131230785;
			
			// aapt resource value: 0x7f080049
			public const int Widget_AppCompat_Light_Base_ActionBar_TabBar = 2131230793;
			
			// aapt resource value: 0x7f08004a
			public const int Widget_AppCompat_Light_Base_ActionBar_TabBar_Inverse = 2131230794;
			
			// aapt resource value: 0x7f08004f
			public const int Widget_AppCompat_Light_Base_ActionBar_TabText = 2131230799;
			
			// aapt resource value: 0x7f080050
			public const int Widget_AppCompat_Light_Base_ActionBar_TabText_Inverse = 2131230800;
			
			// aapt resource value: 0x7f08004c
			public const int Widget_AppCompat_Light_Base_ActionBar_TabView = 2131230796;
			
			// aapt resource value: 0x7f08004d
			public const int Widget_AppCompat_Light_Base_ActionBar_TabView_Inverse = 2131230797;
			
			// aapt resource value: 0x7f080043
			public const int Widget_AppCompat_Light_Base_ActionButton = 2131230787;
			
			// aapt resource value: 0x7f080045
			public const int Widget_AppCompat_Light_Base_ActionButton_CloseMode = 2131230789;
			
			// aapt resource value: 0x7f080047
			public const int Widget_AppCompat_Light_Base_ActionButton_Overflow = 2131230791;
			
			// aapt resource value: 0x7f080052
			public const int Widget_AppCompat_Light_Base_ActionMode_Inverse = 2131230802;
			
			// aapt resource value: 0x7f080079
			public const int Widget_AppCompat_Light_Base_ActivityChooserView = 2131230841;
			
			// aapt resource value: 0x7f080077
			public const int Widget_AppCompat_Light_Base_AutoCompleteTextView = 2131230839;
			
			// aapt resource value: 0x7f080061
			public const int Widget_AppCompat_Light_Base_DropDownItem_Spinner = 2131230817;
			
			// aapt resource value: 0x7f080069
			public const int Widget_AppCompat_Light_Base_ListPopupWindow = 2131230825;
			
			// aapt resource value: 0x7f080063
			public const int Widget_AppCompat_Light_Base_ListView_DropDown = 2131230819;
			
			// aapt resource value: 0x7f08006b
			public const int Widget_AppCompat_Light_Base_PopupMenu = 2131230827;
			
			// aapt resource value: 0x7f08005f
			public const int Widget_AppCompat_Light_Base_Spinner = 2131230815;
			
			// aapt resource value: 0x7f080028
			public const int Widget_AppCompat_Light_DropDownItem_Spinner = 2131230760;
			
			// aapt resource value: 0x7f08002d
			public const int Widget_AppCompat_Light_ListPopupWindow = 2131230765;
			
			// aapt resource value: 0x7f08002a
			public const int Widget_AppCompat_Light_ListView_DropDown = 2131230762;
			
			// aapt resource value: 0x7f08002f
			public const int Widget_AppCompat_Light_PopupMenu = 2131230767;
			
			// aapt resource value: 0x7f080026
			public const int Widget_AppCompat_Light_Spinner_DropDown_ActionBar = 2131230758;
			
			// aapt resource value: 0x7f08002c
			public const int Widget_AppCompat_ListPopupWindow = 2131230764;
			
			// aapt resource value: 0x7f080029
			public const int Widget_AppCompat_ListView_DropDown = 2131230761;
			
			// aapt resource value: 0x7f080030
			public const int Widget_AppCompat_ListView_Menu = 2131230768;
			
			// aapt resource value: 0x7f08002e
			public const int Widget_AppCompat_PopupMenu = 2131230766;
			
			// aapt resource value: 0x7f08000d
			public const int Widget_AppCompat_ProgressBar = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int Widget_AppCompat_ProgressBar_Horizontal = 2131230732;
			
			// aapt resource value: 0x7f080025
			public const int Widget_AppCompat_Spinner_DropDown_ActionBar = 2131230757;
			
			// aapt resource value: 0x7f08009c
			public const int com_facebook_auth_dialog = 2131230876;
			
			// aapt resource value: 0x7f08009d
			public const int com_facebook_button = 2131230877;
			
			// aapt resource value: 0x7f08009e
			public const int com_facebook_button_like = 2131230878;
			
			// aapt resource value: 0x7f08009f
			public const int com_facebook_button_send = 2131230879;
			
			// aapt resource value: 0x7f0800a0
			public const int com_facebook_button_share = 2131230880;
			
			// aapt resource value: 0x7f0800a1
			public const int com_facebook_loginview_default_style = 2131230881;
			
			// aapt resource value: 0x7f0800a2
			public const int com_facebook_loginview_silver_style = 2131230882;
			
			// aapt resource value: 0x7f0800a3
			public const int tooltip_bubble_text = 2131230883;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[]
			{
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034};
			
			// aapt resource value: 10
			public const int ActionBar_background = 10;
			
			// aapt resource value: 12
			public const int ActionBar_backgroundSplit = 12;
			
			// aapt resource value: 11
			public const int ActionBar_backgroundStacked = 11;
			
			// aapt resource value: 13
			public const int ActionBar_customNavigationLayout = 13;
			
			// aapt resource value: 3
			public const int ActionBar_displayOptions = 3;
			
			// aapt resource value: 9
			public const int ActionBar_divider = 9;
			
			// aapt resource value: 1
			public const int ActionBar_height = 1;
			
			// aapt resource value: 14
			public const int ActionBar_homeLayout = 14;
			
			// aapt resource value: 7
			public const int ActionBar_icon = 7;
			
			// aapt resource value: 16
			public const int ActionBar_indeterminateProgressStyle = 16;
			
			// aapt resource value: 18
			public const int ActionBar_itemPadding = 18;
			
			// aapt resource value: 8
			public const int ActionBar_logo = 8;
			
			// aapt resource value: 2
			public const int ActionBar_navigationMode = 2;
			
			// aapt resource value: 17
			public const int ActionBar_progressBarPadding = 17;
			
			// aapt resource value: 15
			public const int ActionBar_progressBarStyle = 15;
			
			// aapt resource value: 4
			public const int ActionBar_subtitle = 4;
			
			// aapt resource value: 6
			public const int ActionBar_subtitleTextStyle = 6;
			
			// aapt resource value: 0
			public const int ActionBar_title = 0;
			
			// aapt resource value: 5
			public const int ActionBar_titleTextStyle = 5;
			
			public static int[] ActionBarLayout = new int[]
			{
					16842931};
			
			// aapt resource value: 0
			public const int ActionBarLayout_android_layout_gravity = 0;
			
			public static int[] ActionBarWindow = new int[]
			{
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 0
			public const int ActionBarWindow_windowActionBar = 0;
			
			// aapt resource value: 1
			public const int ActionBarWindow_windowActionBarOverlay = 1;
			
			// aapt resource value: 6
			public const int ActionBarWindow_windowFixedHeightMajor = 6;
			
			// aapt resource value: 4
			public const int ActionBarWindow_windowFixedHeightMinor = 4;
			
			// aapt resource value: 3
			public const int ActionBarWindow_windowFixedWidthMajor = 3;
			
			// aapt resource value: 5
			public const int ActionBarWindow_windowFixedWidthMinor = 5;
			
			// aapt resource value: 2
			public const int ActionBarWindow_windowSplitActionBar = 2;
			
			public static int[] ActionMenuItemView = new int[]
			{
					16843071};
			
			// aapt resource value: 0
			public const int ActionMenuItemView_android_minWidth = 0;
			
			public static int[] ActionMenuView;
			
			public static int[] ActionMode = new int[]
			{
					2130772017,
					2130772021,
					2130772022,
					2130772026,
					2130772028};
			
			// aapt resource value: 3
			public const int ActionMode_background = 3;
			
			// aapt resource value: 4
			public const int ActionMode_backgroundSplit = 4;
			
			// aapt resource value: 0
			public const int ActionMode_height = 0;
			
			// aapt resource value: 2
			public const int ActionMode_subtitleTextStyle = 2;
			
			// aapt resource value: 1
			public const int ActionMode_titleTextStyle = 1;
			
			public static int[] ActivityChooserView = new int[]
			{
					2130772085,
					2130772086};
			
			// aapt resource value: 1
			public const int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
			
			// aapt resource value: 0
			public const int ActivityChooserView_initialActivityCount = 0;
			
			public static int[] CardView = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			public static int[] CompatTextView = new int[]
			{
					2130772088};
			
			// aapt resource value: 0
			public const int CompatTextView_textAllCaps = 0;
			
			public static int[] LinearLayoutICS = new int[]
			{
					2130772025,
					2130772064,
					2130772065};
			
			// aapt resource value: 0
			public const int LinearLayoutICS_divider = 0;
			
			// aapt resource value: 2
			public const int LinearLayoutICS_dividerPadding = 2;
			
			// aapt resource value: 1
			public const int LinearLayoutICS_showDividers = 1;
			
			public static int[] MenuGroup = new int[]
			{
					16842766,
					16842960,
					16843156,
					16843230,
					16843231,
					16843232};
			
			// aapt resource value: 5
			public const int MenuGroup_android_checkableBehavior = 5;
			
			// aapt resource value: 0
			public const int MenuGroup_android_enabled = 0;
			
			// aapt resource value: 1
			public const int MenuGroup_android_id = 1;
			
			// aapt resource value: 3
			public const int MenuGroup_android_menuCategory = 3;
			
			// aapt resource value: 4
			public const int MenuGroup_android_orderInCategory = 4;
			
			// aapt resource value: 2
			public const int MenuGroup_android_visible = 2;
			
			public static int[] MenuItem = new int[]
			{
					16842754,
					16842766,
					16842960,
					16843014,
					16843156,
					16843230,
					16843231,
					16843233,
					16843234,
					16843235,
					16843236,
					16843237,
					16843375,
					2130772056,
					2130772057,
					2130772058,
					2130772059};
			
			// aapt resource value: 14
			public const int MenuItem_actionLayout = 14;
			
			// aapt resource value: 16
			public const int MenuItem_actionProviderClass = 16;
			
			// aapt resource value: 15
			public const int MenuItem_actionViewClass = 15;
			
			// aapt resource value: 9
			public const int MenuItem_android_alphabeticShortcut = 9;
			
			// aapt resource value: 11
			public const int MenuItem_android_checkable = 11;
			
			// aapt resource value: 3
			public const int MenuItem_android_checked = 3;
			
			// aapt resource value: 1
			public const int MenuItem_android_enabled = 1;
			
			// aapt resource value: 0
			public const int MenuItem_android_icon = 0;
			
			// aapt resource value: 2
			public const int MenuItem_android_id = 2;
			
			// aapt resource value: 5
			public const int MenuItem_android_menuCategory = 5;
			
			// aapt resource value: 10
			public const int MenuItem_android_numericShortcut = 10;
			
			// aapt resource value: 12
			public const int MenuItem_android_onClick = 12;
			
			// aapt resource value: 6
			public const int MenuItem_android_orderInCategory = 6;
			
			// aapt resource value: 7
			public const int MenuItem_android_title = 7;
			
			// aapt resource value: 8
			public const int MenuItem_android_titleCondensed = 8;
			
			// aapt resource value: 4
			public const int MenuItem_android_visible = 4;
			
			// aapt resource value: 13
			public const int MenuItem_showAsAction = 13;
			
			public static int[] MenuView = new int[]
			{
					16842926,
					16843052,
					16843053,
					16843054,
					16843055,
					16843056,
					16843057,
					16843829};
			
			// aapt resource value: 4
			public const int MenuView_android_headerBackground = 4;
			
			// aapt resource value: 2
			public const int MenuView_android_horizontalDivider = 2;
			
			// aapt resource value: 5
			public const int MenuView_android_itemBackground = 5;
			
			// aapt resource value: 6
			public const int MenuView_android_itemIconDisabledAlpha = 6;
			
			// aapt resource value: 1
			public const int MenuView_android_itemTextAppearance = 1;
			
			// aapt resource value: 7
			public const int MenuView_android_preserveIconSpacing = 7;
			
			// aapt resource value: 3
			public const int MenuView_android_verticalDivider = 3;
			
			// aapt resource value: 0
			public const int MenuView_android_windowAnimationStyle = 0;
			
			public static int[] SearchView = new int[]
			{
					16843039,
					16843296,
					16843364,
					2130772069,
					2130772070};
			
			// aapt resource value: 2
			public const int SearchView_android_imeOptions = 2;
			
			// aapt resource value: 1
			public const int SearchView_android_inputType = 1;
			
			// aapt resource value: 0
			public const int SearchView_android_maxWidth = 0;
			
			// aapt resource value: 3
			public const int SearchView_iconifiedByDefault = 3;
			
			// aapt resource value: 4
			public const int SearchView_queryHint = 4;
			
			public static int[] Spinner = new int[]
			{
					16842927,
					16843125,
					16843126,
					16843362,
					16843436,
					16843437,
					2130772060,
					2130772061,
					2130772062,
					2130772063};
			
			// aapt resource value: 4
			public const int Spinner_android_dropDownHorizontalOffset = 4;
			
			// aapt resource value: 1
			public const int Spinner_android_dropDownSelector = 1;
			
			// aapt resource value: 5
			public const int Spinner_android_dropDownVerticalOffset = 5;
			
			// aapt resource value: 3
			public const int Spinner_android_dropDownWidth = 3;
			
			// aapt resource value: 0
			public const int Spinner_android_gravity = 0;
			
			// aapt resource value: 2
			public const int Spinner_android_popupBackground = 2;
			
			// aapt resource value: 9
			public const int Spinner_disableChildrenWhenDisabled = 9;
			
			// aapt resource value: 8
			public const int Spinner_popupPromptView = 8;
			
			// aapt resource value: 6
			public const int Spinner_prompt = 6;
			
			// aapt resource value: 7
			public const int Spinner_spinnerMode = 7;
			
			public static int[] Theme = new int[]
			{
					2130772050,
					2130772051,
					2130772052,
					2130772053,
					2130772054,
					2130772055};
			
			// aapt resource value: 0
			public const int Theme_actionDropDownStyle = 0;
			
			// aapt resource value: 1
			public const int Theme_dropdownListPreferredItemHeight = 1;
			
			// aapt resource value: 5
			public const int Theme_listChoiceBackgroundIndicator = 5;
			
			// aapt resource value: 4
			public const int Theme_panelMenuListTheme = 4;
			
			// aapt resource value: 3
			public const int Theme_panelMenuListWidth = 3;
			
			// aapt resource value: 2
			public const int Theme_popupMenuStyle = 2;
			
			public static int[] View = new int[]
			{
					16842970,
					2130772035,
					2130772036};
			
			// aapt resource value: 0
			public const int View_android_focusable = 0;
			
			// aapt resource value: 2
			public const int View_paddingEnd = 2;
			
			// aapt resource value: 1
			public const int View_paddingStart = 1;
			
			public static int[] com_facebook_like_view = new int[]
			{
					2130772089,
					2130772090,
					2130772091,
					2130772092,
					2130772093,
					2130772094};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[]
			{
					2130772095,
					2130772096,
					2130772097,
					2130772098};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[]
			{
					2130772099,
					2130772100};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
